osx_image: xcode8
language: objective-c
env:
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
script:
  - set -o pipefail && xcodebuild -scheme JSONThemeKit -destination "$DESTINATION" $ACTION | xcpretty
